[package]
name = "automation-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
automation-api = { path = "../automation-api" }
automation-browser = { path = "../automation-browser" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
openrouter-rs = { workspace = true }
uuid = { workspace = true }
futures-util.workspace = true
dotenvy.workspace = true
automation-integration = { path = "../automation-integration" } 